### ISSUE TITLE
Should not recommend world writeable permissions

### ISSUE THREAD

**Issue by brianmacy** [Senzing/docker-compose-demo#62]
In the README.md we recommend the following for RabbitMQ.  We should choose something more specific.

sudo chmod 777 ${RABBITMQ_DIR}

BrianM

**Comment by brianmacy** [comment]
https://github.com/Senzing/docker-compose-demo/blob/master/docs/docker-compose-rabbitmq-postgresql/README.md
https://github.com/Senzing/docker-compose-demo/blob/master/docs/docker-compose-rabbitmq-mysql/README.md

**Comment by jeffadair** [comment]
I changed my permissions to 077 on my existing setup and had no issues.

**Comment by jeffadair** [comment]
037 seems like the minimal permissions needed to bring up a formation from scratch. @docktermj Does that sound correct? Should I go with this?

**Comment by docktermj** [comment]
@jeffadair  Are you thinking

```
rwx-wx---
```
Which is 730.  (user, group, other)

**Comment by jeffadair** [comment]
Oh wow. I've had that backwards in my head for... I don't know how long. I was thinking largest group->smallest group instead of smallest->largest. Thanks for helping me realize that!

But 037 did work, so I tried 030 and that works too for my test. We use non-durable queues so it avoids writing to disk if at all possible. I've seen it write when the queues get large, so 030 may be overly restrictive in that situation.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/docker-compose-demo/pull/155
- https://github.com/Senzing/docker-compose-demo/pull/248
