### ISSUE TITLE
rabbitmq-postgres issue

### ISSUE THREAD

**Issue by hanifa2102** [Senzing/docker-compose-demo#75]
**Describe the bug**
Following the steps here, [README.md](https://github.com/Senzing/docker-compose-demo/blob/master/docs/docker-compose-rabbitmq-postgresql/README.md), I set up the docker containers. However, I realised that postgres database is empty.

**Environment**
- Ubuntu VM in Google Cloud Compute
- Latest pull of docker-compose-demo

**To Reproduce**

> export GIT_ACCOUNT=senzing
> export GIT_REPOSITORY=docker-compose-demo
> export GIT_ACCOUNT_DIR=~/${GIT_ACCOUNT}.git
> export GIT_REPOSITORY_DIR="${GIT_ACCOUNT_DIR}/${GIT_REPOSITORY}"
> 
> export SENZING_VOLUME=/opt/senzing
> 
> export SENZING_DATA_DIR=${SENZING_VOLUME}/data
> export SENZING_DATA_VERSION_DIR=${SENZING_DATA_DIR}/1.0.0
> export SENZING_ETC_DIR=${SENZING_VOLUME}/etc
> export SENZING_G2_DIR=${SENZING_VOLUME}/g2
> export SENZING_VAR_DIR=${SENZING_VOLUME}/var
> 
> export POSTGRES_DIR=${SENZING_VAR_DIR}/postgres
> export RABBITMQ_DIR=${SENZING_VAR_DIR}/rabbitmq
> 
> sudo mkdir -p ${RABBITMQ_DIR}
> sudo chmod 777 ${RABBITMQ_DIR}
> 
> cd ${GIT_REPOSITORY_DIR}
> sudo \
>   --preserve-env \
>   docker-compose --file resources/postgresql/docker-compose-rabbitmq-postgresql.yaml up | tee logs/260320.log
> 

4. Error Log attached.
[260320.log](https://github.com/Senzing/docker-compose-demo/files/4385250/260320.log)
> ERROR:  column "lock_dsrc_action" does not exist at character 8

**Comment by brianmacy** [comment]
I can't help with the overall item -- Michael will get to that -- but that PostgreSQL error can be ignored.  That is simply the engine detecting whether or not an optional (future) column exists to self-configure its behavior.

**Comment by brianmacy** [comment]
Looking a bit more at this, you are using the default 10k record license and, I believe, trying to load 1M records.

[34;1msenzing-stream-loader |[0m 2020-03-26 03:59:25,941 senzing-50010160I -------------------- LICENSE --------------------
[34;1msenzing-stream-loader |[0m 2020-03-26 03:59:25,941 senzing-50010161I           Version: 1.14.6 (2020-03-23)
[34;1msenzing-stream-loader |[0m 2020-03-26 03:59:25,941 senzing-50010162I          Customer: 
[34;1msenzing-stream-loader |[0m 2020-03-26 03:59:25,941 senzing-50010163I              Type: EVAL
[34;1msenzing-stream-loader |[0m 2020-03-26 03:59:25,941 senzing-50010164I   Expiration date: 2020-09-22
[34;1msenzing-stream-loader |[0m 2020-03-26 03:59:25,943 senzing-50010165I   Expiration time: 179 days until expiration
[34;1msenzing-stream-loader |[0m 2020-03-26 03:59:25,943 senzing-50010166I           Records: 10000
[34;1msenzing-stream-loader |[0m 2020-03-26 03:59:25,943 senzing-50010167I          Contract: 
[34;1msenzing-stream-loader |[0m 2020-03-26 03:59:25,944 senzing-50010299I -------------------------------------------------

**Comment by docktermj** [comment]
@hanifa2102, Is the `docker-compose-rabbitmq-postgresql.yaml` file exactly like https://github.com/Senzing/docker-compose-demo/blob/master/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml or has it been modified?   In my investigation, I'm going to assume that the files are identical.

The root of the problem is what is seen at the log beginning at Line 76:
```
[32;1msenzing-postgresql-init |[0m psql: could not connect to server: Connection refused
[32;1msenzing-postgresql-init |[0m 	Is the server running on host "senzing-postgres" (172.20.0.4) and accepting
[32;1msenzing-postgresql-init |[0m 	TCP/IP connections on port 5432?
[33;1msenzing-postgres |[0m selecting default shared_buffers ... 128MB
[36;1msenzing-phppgadmin |[0m - runit: enter stage: /etc/runit/2
[33;1msenzing-postgres |[0m selecting default timezone ... Etc/UTC
[33;1msenzing-postgres |[0m selecting dynamic shared memory implementation ... posix
[33;1msenzing-postgres |[0m creating configuration files ... ok
[32;1msenzing-postgresql-init exited with code 0
```
The `senzing-postgresql-init` container doesn't complete successfully. (Even though it exits with code 0)  This is the container that initializes the PostgreSQL database with tables, indexes, etc.  It's running before the database is ready.  So it's the reason why your database is empty.

The container is supposed to restart on failure (https://github.com/Senzing/docker-compose-demo/blob/1021e890b9f453909861c725504d8237dbe0bbea/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml#L66), but we see the following in the log:
```
[32;1msenzing-postgresql-init exited with code 0
```
So restart doesn't occur.

This is happening because of a "race condition".  `senzing-postgres-init` is running before `senzing-postgres` is available.  So you can try to run the docker-compose formation again and perhaps the initialization will occur.

In the meantime,  meaning today,   I'll be looking for a way to serialize `senzing-postgresql` and `senzing-postgresql-init` so that the race condition is avoided.  I'm pondering the following approaches:

1. Have `senzing-postgresql-init` return non-zero  (if I can detect that condition)
1. "Sleep" the `senzing-postgresql-init` container to allow `senzing-postgresql` to come up.  (The issue with this is exactly how long to "sleep"
1. Create a readiness test for `senzing-postgresql-init` to verify that `senzing-postgresql` is ready.  (Not sure this is possible)
1. Hopefully something better.

I'll post any progress in this issue.

@hanifa2102, If you do re-run the docker-compose formation, let me know if it succeeds or fails again.

**Comment by docktermj** [comment]
@hanifa2102 Thanks for finding these race-conditions.  Your machine must be much faster than mine,  I haven't seen them, so I'm glad you are reporting them.

**Comment by docktermj** [comment]
Journal notes:

`senzing-postgresql-init` is really `jbergknoff/postgresql-client`  https://github.com/Senzing/docker-compose-demo/blob/1021e890b9f453909861c725504d8237dbe0bbea/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml#L63

That docker image is stored at https://hub.docker.com/r/jbergknoff/postgresql-client and has a very minimal Dockerfile https://hub.docker.com/r/jbergknoff/postgresql-client/dockerfile

So that means we either "slow down" the image in docker-compose YAML somehow or wrap `jbergknoff/postgresql-client`.

**Comment by docktermj** [comment]
Just ran the `docker-compose-rabbitmq-postgresql.yaml` docker-compose formation.  Here's what I see in the log for `senzing-postgres-init`:

```
psql: could not connect to server: Connection refused
	Is the server running on host senzing-postgres (172.20.0.2) and accepting
	TCP/IP connections on port 5432?
CREATE TABLE
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
INSERT 0 1
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
DELETE 0
INSERT 0 1
```
What's interesting is that the same questions are asked as in the error log, but it still creates tables, indexes, and rows.

@hanifa2102 By any chance are you using "Portainer"? (https://github.com/Senzing/docker-compose-demo/blob/master/docs/docker-compose-rabbitmq-postgresql/README.md#view-docker-containers)  It will show logs from only the `senzing-postgres-init` container.   I just want to verify whether `senzing-postgresql-init` did or didn't create tables.

**Comment by docktermj** [comment]
I'm still thinking "race-condition" because after `senzing-postgresql-init` completes, in
[260320.log](https://github.com/Senzing/docker-compose-demo/files/4385250/260320.log)
we see on line #102:
```
[33;1msenzing-postgres |[0m Success. You can now start the database server using:
```
So `senzing-postgresql` says it's ready *after* `senzing-postgresql-init` has exited.

**Comment by docktermj** [comment]
Development note: 

This issue is between 2 docker images that are not owned by Senzing:

1. https://github.com/Senzing/docker-compose-demo/blob/1021e890b9f453909861c725504d8237dbe0bbea/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml#L46
2. https://github.com/Senzing/docker-compose-demo/blob/1021e890b9f453909861c725504d8237dbe0bbea/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml#L63

**Comment by docktermj** [comment]
Development note:

Possible fixes in the `postgres:11.6` deployment
1. Add `healthcheck` 
    1. https://github.com/peter-evans/docker-compose-healthcheck)
    1. https://www.postgresql.org/docs/9.4/app-pg-isready.html

Possible fixes in the `jbergknoff/postgresql-client` deployment
1. `pgsql` parameters
    1. https://www.postgresql.org/docs/10/app-psql.html

**Comment by docktermj** [comment]
I got the "go ahead" to make a new version of the postgresql client.  https://github.com/Senzing/postgresql-client.  So I'll be working on that now.

**Comment by docktermj** [comment]
@hanifa2102 I've made a change to `resources/postgresql/docker-compose-rabbitmq-postgresql.yaml` to utilize the new `senzing/postgresql-client` docker image.   It should fix the issue you are seeing.

Please do a `git pull` in the repository to download the new YAML files and give it another try.   Let me know if there are any more issues.

**Comment by hanifa2102** [comment]
Hi @docktermj,
    Running on my desktop, i was able to see the records being written into the postgres database as well as the results in the web app. That's good.
However, for provisioning, we are testing it out on a much biggest instance in the gcp. This has like 15GB of memory compared to my machines 8Gb. And again, there was this siimlar error.
[300320_1.log](https://github.com/Senzing/docker-compose-demo/files/4402152/300320_1.log)

Thanks
Hanifa

**Comment by brianmacy** [comment]
@hanifa2102 what error?

BrianM

**Comment by docktermj** [comment]
What is seen in the log:

1) *Good Thing:* The `mock-data-generator` delivered 5000 records to RabbitMQ and then shutdown properly.
 ```
[32;1msenzing-mock-data-generator |[0m 2020-03-30 10:07:16,542 senzing-50020106D Records sent to RabbitMQ: 5000
```
2) *Good Thing:*  The `stream-loader` starts up and connects to RabbitMQ with 4 threads.
```
[34;1msenzing-stream-loader |[0m 2020-03-30 10:08:05,311 senzing-50010129I RabbitMQProcess-0-thread-0 is running.
[34;1msenzing-stream-loader |[0m 2020-03-30 10:08:05,313 senzing-50010129I RabbitMQProcess-0-thread-1 is running.
[34;1msenzing-stream-loader |[0m 2020-03-30 10:08:05,313 senzing-50010129I RabbitMQProcess-0-thread-2 is running.
[34;1msenzing-stream-loader |[0m 2020-03-30 10:08:05,316 senzing-50010129I RabbitMQProcess-0-thread-3 is running.
[34;1msenzing-stream-loader |[0m 2020-03-30 10:08:05,325 Pika version 1.1.0 connecting to ('172.20.0.2', 5672)
[34;1msenzing-stream-loader |[0m 2020-03-30 10:08:05,325 Pika version 1.1.0 connecting to ('172.20.0.2', 5672)
[34;1msenzing-stream-loader |[0m 2020-03-30 10:08:05,326 Pika version 1.1.0 connecting to ('172.20.0.2', 5672)
[34;1msenzing-stream-loader |[0m 2020-03-30 10:08:05,326 Pika version 1.1.0 connecting to ('172.20.0.2', 5672)
:
[35;1msenzing-rabbitmq |[0m 2020-03-30 10:08:05.344 [info] <0.691.0> connection <0.691.0> (172.20.0.9:56982 -> 172.20.0.2:5672): user 'user' authenticated and granted access to vhost '/'
[35;1msenzing-rabbitmq |[0m 2020-03-30 10:08:05.345 [info] <0.688.0> connection <0.688.0> (172.20.0.9:56980 -> 172.20.0.2:5672): user 'user' authenticated and granted access to vhost '/'
[35;1msenzing-rabbitmq |[0m 2020-03-30 10:08:05.349 [info] <0.697.0> connection <0.697.0> (172.20.0.9:56986 -> 172.20.0.2:5672): user 'user' authenticated and granted access to vhost '/'
[35;1msenzing-rabbitmq |[0m 2020-03-30 10:08:05.353 [info] <0.694.0> connection <0.694.0> (172.20.0.9:56984 -> 172.20.0.2:5672): user 'user' authenticated and granted access to vhost '/'
```

3) *Bad Thing:*  The `stream-loader` doesn't process any records.  
```
[34;1msenzing-stream-loader |[0m 2020-03-30 10:21:05,661 senzing-50010127I Monitor: {"processed_records_interval": 0, "processed_records_total": 0, "queued_records_interval": 0, "queued_records_total": 0, "rate_processed_interval": 0, "rate_processed_total": 0, "rate_queued_interval": 0, "rate_queued_total": 0, "uptime": 843, "workers_active": 4, "workers_total": 4}
```

4) *Bad Thing:*  Right in the middle of loading RabbitMQ, RabbitMQ stops.  Line #554:
```
[0m[32;1msenzing-mock-data-generator |[0m 2020-03-30 10:07:14,786 senzing-50020106D Records sent to RabbitMQ: 1000
[32;1msenzing-mock-data-generator |[0m 2020-03-30 10:07:15,233 senzing-50020106D Records sent to RabbitMQ: 2000
[32;1msenzing-mock-data-generator |[0m 2020-03-30 10:07:15,689 senzing-50020106D Records sent to RabbitMQ: 3000
[32;1msenzing-mock-data-generator |0m 2020-03-30 10:07:16,126 senzing-50020106D Records sent to RabbitMQ: 4000
[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:07:16.38 [0m[38;5;2mINFO[0m ==> Stopping RabbitMQ...
[32;1msenzing-mock-data-generator |[0m 2020-03-30 10:07:16,542 senzing-50020106D Records sent to RabbitMQ: 5000
[32;1msenzing-mock-data-generator |[0m 2020-03-30 10:07:16,544 Closing connection (200): Normal shutdown
```
Then later in the log file RabbitMQ starts again.  Line #634:
```
[0m[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:07:22.75 [0m[38;5;2mINFO [0m ==> ** RabbitMQ setup finished! **
[35;1msenzing-rabbitmq |[0m 
[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:07:22.76 [0m[38;5;2mINFO [0m ==> ** Starting RabbitMQ **
```
I'm guessing that all of the records in the RabbitMQ Queue have disappeared.

4) *Good Thing:* The database is connectable.
```
[32msenzing-init-container |[0m 2020-03-30 10:07:32,382 senzing-50070170I Created new default config in SYS_CFG having ID 3763835201
```

Given these things, the issue is somewhere between RabbitMQ and `stream-loader.py`.   Or solely within one of the programs.   We'll need to debug a bit.

@hanifa2102 

When running, do you see 5000 records in RabbitMQ?  That is:
1) View RabbitMQ as described at https://github.com/Senzing/docker-compose-demo/tree/master/docs/docker-compose-rabbitmq-postgresql#view-rabbitmq 
2) "Overview" tab >  "Queued messages" graph
3) Does the chart go from 0 to 5K then start coming down as records are consumed?

For the next run of the system, we'll add additional logging for the `senzing/stream-loader` container.  
1) Assuming you are running with `docker-compose-rabbitmq-postgresql.yaml`, In your local copy of  that file modify https://github.com/Senzing/docker-compose-demo/blob/21ec7f3d50fc84c9b318a7aab9fa761a8fd8ac17/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml#L139-L151 and add
```
      SENZING_LOG_LEVEL: debug
```
 to the `environment:` section.   Creating something like this:
```
:
  loader:
    container_name: senzing-stream-loader
    depends_on:
      - rabbitmq
      - postgres
    environment:
      LC_CTYPE: en_US.utf8
#     See https://github.com/Senzing/stream-loader#configuration
      SENZING_DATA_SOURCE: ${SENZING_DATA_SOURCE:-TEST}
      SENZING_DATABASE_URL: "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@senzing-postgres:5432/${POSTGRES_DB:-G2}"
      SENZING_DELAY_IN_SECONDS: 60
      SENZING_ENTITY_TYPE: ${SENZING_ENTITY_TYPE:-TEST}
      SENZING_LOG_LEVEL: debug
      SENZING_MONITORING_PERIOD_IN_SECONDS: ${SENZING_MONITORING_PERIOD_IN_SECONDS:-60}
:
```

**Comment by docktermj** [comment]
Hmm.  Another thought. Here's the sequence:

RabbitMQ starts it's "setup" at Line #96.
```
[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:06:57.91 [0m[38;5;2mINFO [0m ==> ** Starting RabbitMQ setup **
[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:06:57.92 [0m[38;5;2mINFO [0m ==> Validating settings in RABBITMQ_* env vars..
[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:06:57.94 [0m[38;5;2mINFO [0m ==> Initializing RabbitMQ...
[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:06:57.96 [0m[38;5;2mINFO [0m ==> Generating random cookie
[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:06:58.01 [0m[38;5;2mINFO [0m ==> Starting RabbitMQ in background...
```

`senzing-mock-data-generator` starts sending records to RabbitMQ *before* RabbitMQ setup is complete at Line #554.
```
[0m[32;1msenzing-mock-data-generator |[0m 2020-03-30 10:07:14,786 senzing-50020106D Records sent to RabbitMQ: 1000
```

RabbitMQ "restarts" to complete it's setup at Line #558.
```
[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:07:16.38 [0m[38;5;2mINFO [0m ==> Stopping RabbitMQ...
```

RabbitMQ completes its setup and restarts at Line #634.
```
[0m[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:07:22.75 [0m[38;5;2mINFO [0m ==> ** RabbitMQ setup finished! **
[35;1msenzing-rabbitmq |[0m 
[35;1msenzing-rabbitmq |[0m [38;5;6m [38;5;5m10:07:22.76 [0m[38;5;2mINFO [0m ==> ** Starting RabbitMQ **
```

But this is after `mock-data-generator` thinks it's delivered the 5000 messages.  So I'm guessing that the message are lost.

@hanifa2102 I believe you've found another "race condition" between containers in the docker-compose formation.   I congratulate you!  

I've opened up https://github.com/Senzing/mock-data-generator/issues/41 to work on this issue.  I should have something ready by end of day.

I'll report back in this issue when I have the fix in place.

Again, thank you!

**Comment by docktermj** [comment]
@hanifa2102 I've created a new `senzing/mock-data-generator:1.1.1` docker image  (https://hub.docker.com/r/senzing/mock-data-generator/tags) and updated docker-compose YAML files to utilize the new docker image.  Example: https://github.com/Senzing/docker-compose-demo/blob/caa28987b81290016419fef131fe9db9daacbfa5/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml#L35

So get the latest version of the ~/senzing.git/docker-compose-demo repository.  Example:
```
cd ~/senzing.git/docker-compose-demo
git pull
```
and try your test again.

As always, let me know if there are any issues.

**Comment by hanifa2102** [comment]
Thanks, it works now.

**Comment by docktermj** [comment]
@hanifa2102 I'm delighted to hear that.  And I'm appreciative that you found this problem.   Please let us know of any other hurdles that might come your way.  We want this to be a good experience for you.
